// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mtableFieldNames          = builder.RawFieldNames(&Mtable{})
	mtableRows                = strings.Join(mtableFieldNames, ",")
	mtableRowsExpectAutoSet   = strings.Join(stringx.Remove(mtableFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	mtableRowsWithPlaceHolder = strings.Join(stringx.Remove(mtableFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheMtableIdPrefix = "cache:mtable:id:"
)

type (
	mtableModel interface {
		Insert(ctx context.Context, data *Mtable) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Mtable, error)
		Update(ctx context.Context, data *Mtable) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMtableModel struct {
		sqlc.CachedConn
		table string
	}

	Mtable struct {
		Id   int64  `db:"id"`   // ID
		Name string `db:"name"` // 名称
	}
)

func newMtableModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultMtableModel {
	return &defaultMtableModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`mtable`",
	}
}

func (m *defaultMtableModel) Delete(ctx context.Context, id int64) error {
	mtableIdKey := fmt.Sprintf("%s%v", cacheMtableIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mtableIdKey)
	return err
}

func (m *defaultMtableModel) FindOne(ctx context.Context, id int64) (*Mtable, error) {
	mtableIdKey := fmt.Sprintf("%s%v", cacheMtableIdPrefix, id)
	var resp Mtable
	err := m.QueryRowCtx(ctx, &resp, mtableIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mtableRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMtableModel) Insert(ctx context.Context, data *Mtable) (sql.Result, error) {
	mtableIdKey := fmt.Sprintf("%s%v", cacheMtableIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, mtableRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, mtableIdKey)
	return ret, err
}

func (m *defaultMtableModel) Update(ctx context.Context, data *Mtable) error {
	mtableIdKey := fmt.Sprintf("%s%v", cacheMtableIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mtableRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Id)
	}, mtableIdKey)
	return err
}

func (m *defaultMtableModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheMtableIdPrefix, primary)
}

func (m *defaultMtableModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mtableRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMtableModel) tableName() string {
	return m.table
}
