// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"demo/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/mapi/get/:id",
				Handler: getMapiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/mrpc/get/:id",
				Handler: getMrpcHandler(serverCtx),
			},
		},
	)
}
