// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: mrpc.proto

package mrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MrpcClient is the client API for Mrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MrpcClient interface {
	GetById(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Reply, error)
}

type mrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewMrpcClient(cc grpc.ClientConnInterface) MrpcClient {
	return &mrpcClient{cc}
}

func (c *mrpcClient) GetById(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/mrpc.Mrpc/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MrpcServer is the server API for Mrpc service.
// All implementations must embed UnimplementedMrpcServer
// for forward compatibility
type MrpcServer interface {
	GetById(context.Context, *Req) (*Reply, error)
	mustEmbedUnimplementedMrpcServer()
}

// UnimplementedMrpcServer must be embedded to have forward compatible implementations.
type UnimplementedMrpcServer struct {
}

func (UnimplementedMrpcServer) GetById(context.Context, *Req) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedMrpcServer) mustEmbedUnimplementedMrpcServer() {}

// UnsafeMrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MrpcServer will
// result in compilation errors.
type UnsafeMrpcServer interface {
	mustEmbedUnimplementedMrpcServer()
}

func RegisterMrpcServer(s grpc.ServiceRegistrar, srv MrpcServer) {
	s.RegisterService(&Mrpc_ServiceDesc, srv)
}

func _Mrpc_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MrpcServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mrpc.Mrpc/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MrpcServer).GetById(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// Mrpc_ServiceDesc is the grpc.ServiceDesc for Mrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mrpc.Mrpc",
	HandlerType: (*MrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _Mrpc_GetById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mrpc.proto",
}
